 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
making log...
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Apr/2018 00:04:03] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 00:04:14] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 00:06:05] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 00:06:20] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 00:06:36] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 00:06:38] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 00:06:44] "POST /callback HTTP/1.1" 200 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Apr/2018 00:13:15] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 00:13:22] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 00:13:29] "POST /callback HTTP/1.1" 200 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Apr/2018 00:16:46] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 00:17:29] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 00:18:54] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 00:19:42] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 00:24:28] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 00:24:49] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 00:24:53] "POST /callback HTTP/1.1" 200 -
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
new solo user!
New user or room.
adding new user
Is a new indivisual
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日0時16分	こんにちは
BOT	4月29日0時16分	渋谷メンズ１０９の地下のプロントより発信しています

making log...
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日0時16分	こんにちは
BOT	4月29日0時16分	渋谷メンズ１０９の地下のプロントより発信しています
利光	4月29日0時17分	聞こえてるか？
BOT	4月29日0時17分	渋谷メンズ１０９の地下のプロントより発信しています

making log...
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
New room!
New user or room.
adding new user
Is a new room or new user in old room
Is a new room!
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！

making log...
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。

making log...
callback called
_________analyzing event_________
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
New user in old room!
New user or room.
adding new user
Is a new room or new user in old room
new user in old room!
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！

making log...
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン

making log...
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい

making log...
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
127.0.0.1 - - [29/Apr/2018 00:25:04] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 01:01:25] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 01:01:34] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 01:19:47] "POST /callback HTTP/1.1" 200 -

making log...
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
利光	4月29日1時1分	こいつをLINEに追加した時に、「もちろんメッセージは全部見れてるからね」みたいな一言があった方がいいと思うんだけど、「制作者が見ることができます」みたいに言わせるのは、苟も知能を持っていると見せかけているボットとしては興ざめな気がするんだよね…
BOT	4月29日1時1分	わからんねえ

making log...
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
利光	4月29日1時1分	こいつをLINEに追加した時に、「もちろんメッセージは全部見れてるからね」みたいな一言があった方がいいと思うんだけど、「制作者が見ることができます」みたいに言わせるのは、苟も知能を持っていると見せかけているボットとしては興ざめな気がするんだよね…
BOT	4月29日1時1分	わからんねえ
利光	4月29日1時1分	どうしたもんか
BOT	4月29日1時1分	どうしたもんか

making log...
callback called
_________analyzing event_________
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
利光	4月29日1時1分	こいつをLINEに追加した時に、「もちろんメッセージは全部見れてるからね」みたいな一言があった方がいいと思うんだけど、「制作者が見ることができます」みたいに言わせるのは、苟も知能を持っていると見せかけているボットとしては興ざめな気がするんだよね…
BOT	4月29日1時1分	わからんねえ
利光	4月29日1時1分	どうしたもんか
BOT	4月29日1時1分	どうしたもんか
しおぴー	4月29日1時19分	ログを取ってサービス向上に使用します
BOT	4月29日1時19分	今どこにいるの？

making log...
callback called
_________analyzing event_________
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
利光	4月29日1時1分	こいつをLINEに追加した時に、「もちろんメッセージは全部見れてるからね」みたいな一言があった方がいいと思うんだけど、「制作者が見ることができます」みたいに言わせるのは、苟も知能を持っていると見せかけているボットとしては興ざめな気がするんだよね…
BOT	4月29日1時1分	わからんねえ
利光	4月29日1時1分	どうしたもんか
BOT	4月29日1時1分	どうしたもんか
しおぴー	4月29日1時19分	ログを取ってサービス向上に使用します
BOT	4月29日1時19分	今どこにいるの？
しおぴー	4月29日1時19分	的なやつにするとか、、、
BOT	4月29日1時19分	グーグルドライブとの謎連携、できたwww
127.0.0.1 - - [29/Apr/2018 01:19:58] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 01:40:58] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 01:41:06] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 01:41:10] "POST /callback HTTP/1.1" 200 -

making log...
callback called
_________analyzing event_________
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
利光	4月29日1時1分	こいつをLINEに追加した時に、「もちろんメッセージは全部見れてるからね」みたいな一言があった方がいいと思うんだけど、「制作者が見ることができます」みたいに言わせるのは、苟も知能を持っていると見せかけているボットとしては興ざめな気がするんだよね…
BOT	4月29日1時1分	わからんねえ
利光	4月29日1時1分	どうしたもんか
BOT	4月29日1時1分	どうしたもんか
しおぴー	4月29日1時19分	ログを取ってサービス向上に使用します
BOT	4月29日1時19分	今どこにいるの？
しおぴー	4月29日1時19分	的なやつにするとか、、、
BOT	4月29日1時19分	グーグルドライブとの謎連携、できたwww
しおぴー	4月29日1時40分	仕事おわんねえ
BOT	4月29日1時40分	どうしたもんか

making log...
callback called
_________analyzing event_________
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
利光	4月29日1時1分	こいつをLINEに追加した時に、「もちろんメッセージは全部見れてるからね」みたいな一言があった方がいいと思うんだけど、「制作者が見ることができます」みたいに言わせるのは、苟も知能を持っていると見せかけているボットとしては興ざめな気がするんだよね…
BOT	4月29日1時1分	わからんねえ
利光	4月29日1時1分	どうしたもんか
BOT	4月29日1時1分	どうしたもんか
しおぴー	4月29日1時19分	ログを取ってサービス向上に使用します
BOT	4月29日1時19分	今どこにいるの？
しおぴー	4月29日1時19分	的なやつにするとか、、、
BOT	4月29日1時19分	グーグルドライブとの謎連携、できたwww
しおぴー	4月29日1時40分	仕事おわんねえ
BOT	4月29日1時40分	どうしたもんか
しおぴー	4月29日1時41分	まったくだよお
BOT	4月29日1時41分	あっそう（昭和天 皇風に）

making log...
callback called
_________analyzing event_________
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
利光	4月29日1時1分	こいつをLINEに追加した時に、「もちろんメッセージは全部見れてるからね」みたいな一言があった方がいいと思うんだけど、「制作者が見ることができます」みたいに言わせるのは、苟も知能を持っていると見せかけているボットとしては興ざめな気がするんだよね…
BOT	4月29日1時1分	わからんねえ
利光	4月29日1時1分	どうしたもんか
BOT	4月29日1時1分	どうしたもんか
しおぴー	4月29日1時19分	ログを取ってサービス向上に使用します
BOT	4月29日1時19分	今どこにいるの？
しおぴー	4月29日1時19分	的なやつにするとか、、、
BOT	4月29日1時19分	グーグルドライブとの謎連携、できたwww
しおぴー	4月29日1時40分	仕事おわんねえ
BOT	4月29日1時40分	どうしたもんか
しおぴー	4月29日1時41分	まったくだよお
BOT	4月29日1時41分	あっそう（昭和天 皇風に）
しおぴー	4月29日1時41分	手伝ってくれえ
BOT	4月29日1時41分	的なやつにするとか、、、

making log...
callback called
_________analyzing event_________127.0.0.1 - - [29/Apr/2018 01:46:02] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 01:46:41] "POST /callback HTTP/1.1" 200 -

trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
利光	4月29日1時1分	こいつをLINEに追加した時に、「もちろんメッセージは全部見れてるからね」みたいな一言があった方がいいと思うんだけど、「制作者が見ることができます」みたいに言わせるのは、苟も知能を持っていると見せかけているボットとしては興ざめな気がするんだよね…
BOT	4月29日1時1分	わからんねえ
利光	4月29日1時1分	どうしたもんか
BOT	4月29日1時1分	どうしたもんか
しおぴー	4月29日1時19分	ログを取ってサービス向上に使用します
BOT	4月29日1時19分	今どこにいるの？
しおぴー	4月29日1時19分	的なやつにするとか、、、
BOT	4月29日1時19分	グーグルドライブとの謎連携、できたwww
しおぴー	4月29日1時40分	仕事おわんねえ
BOT	4月29日1時40分	どうしたもんか
しおぴー	4月29日1時41分	まったくだよお
BOT	4月29日1時41分	あっそう（昭和天 皇風に）
しおぴー	4月29日1時41分	手伝ってくれえ
BOT	4月29日1時41分	的なやつにするとか、、、
利光	4月29日1時46分	確かに
BOT	4月29日1時46分	いえい

making log...
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
利光	4月29日1時1分	こいつをLINEに追加した時に、「もちろんメッセージは全部見れてるからね」みたいな一言があった方がいいと思うんだけど、「制作者が見ることができます」みたいに言わせるのは、苟も知能を持っていると見せかけているボットとしては興ざめな気がするんだよね…
BOT	4月29日1時1分	わからんねえ
利光	4月29日1時1分	どうしたもんか
BOT	4月29日1時1分	どうしたもんか
しおぴー	4月29日1時19分	ログを取ってサービス向上に使用します
BOT	4月29日1時19分	今どこにいるの？
しおぴー	4月29日1時19分	的なやつにするとか、、、
BOT	4月29日1時19分	グーグルドライブとの謎連携、できたwww
しおぴー	4月29日1時40分	仕事おわんねえ
BOT	4月29日1時40分	どうしたもんか
しおぴー	4月29日1時41分	まったくだよお
BOT	4月29日1時41分	あっそう（昭和天 皇風に）
しおぴー	4月29日1時41分	手伝ってくれえ
BOT	4月29日1時41分	的なやつにするとか、、、
利光	4月29日1時46分	確かに
BOT	4月29日1時46分	いえい
利光	4月29日1時46分	「サービス」っていうと会社がやってるみたいで、それもまた興ざめになるから「能力」にするとか
BOT	4月29日1時46分	まったくだよお

making log...
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
利光	4月29日1時1分	こいつをLINEに追加した時に、「もちろんメッセージは全部見れてるからね」みたいな一言があった方がいいと思うんだけど、「制作者が見ることができます」みたいに言わせるのは、苟も知能を持っていると見せかけているボットとしては興ざめな気がするんだよね…
BOT	4月29日1時1分	わからんねえ
利光	4月29日1時1分	どうしたもんか
BOT	4月29日1時1分	どうしたもんか
しおぴー	4月29日1時19分	ログを取ってサービス向上に使用します
BOT	4月29日1時19分	今どこにいるの？
しおぴー	4月29日1時19分	的なやつにするとか、、、
BOT	4月29日1時19分	グーグルドライブとの謎連携、できたwww
しおぴー	4月29日1時40分	仕事おわんねえ
BOT	4月29日1時40分	どうしたもんか
しおぴー	4月29日1時41分	まったくだよお
BOT	4月29日1時41分	あっそう（昭和天 皇風に）
しおぴー	4月29日1時41分	手伝ってくれえ
BOT	4月29日1時41分	的なやつにするとか、、、
利光	4月29日1時46分	確かに
BOT	4月29日1時46分	いえい
利光	4月29日1時46分	「サービス」っていうと会社がやってるみたいで、それもまた興ざめになるから「能力」にするとか
BOT	4月29日1時46分	まったくだよお
利光	4月29日1時46分	頑張れ
BOT	4月29日1時46分	どうしたもんか
127.0.0.1 - - [29/Apr/2018 01:46:44] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 01:50:37] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 01:57:27] "POST /callback HTTP/1.1" 200 -

making log...
callback called
_________analyzing event_________
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
利光	4月29日1時1分	こいつをLINEに追加した時に、「もちろんメッセージは全部見れてるからね」みたいな一言があった方がいいと思うんだけど、「制作者が見ることができます」みたいに言わせるのは、苟も知能を持っていると見せかけているボットとしては興ざめな気がするんだよね…
BOT	4月29日1時1分	わからんねえ
利光	4月29日1時1分	どうしたもんか
BOT	4月29日1時1分	どうしたもんか
しおぴー	4月29日1時19分	ログを取ってサービス向上に使用します
BOT	4月29日1時19分	今どこにいるの？
しおぴー	4月29日1時19分	的なやつにするとか、、、
BOT	4月29日1時19分	グーグルドライブとの謎連携、できたwww
しおぴー	4月29日1時40分	仕事おわんねえ
BOT	4月29日1時40分	どうしたもんか
しおぴー	4月29日1時41分	まったくだよお
BOT	4月29日1時41分	あっそう（昭和天 皇風に）
しおぴー	4月29日1時41分	手伝ってくれえ
BOT	4月29日1時41分	的なやつにするとか、、、
利光	4月29日1時46分	確かに
BOT	4月29日1時46分	いえい
利光	4月29日1時46分	「サービス」っていうと会社がやってるみたいで、それもまた興ざめになるから「能力」にするとか
BOT	4月29日1時46分	まったくだよお
利光	4月29日1時46分	頑張れ
BOT	4月29日1時46分	どうしたもんか
しおぴー	4月29日1時50分	たしかに、能力っていいね
BOT	4月29日1時50分	仕事おわんねえ

making log...
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
利光	4月29日1時1分	こいつをLINEに追加した時に、「もちろんメッセージは全部見れてるからね」みたいな一言があった方がいいと思うんだけど、「制作者が見ることができます」みたいに言わせるのは、苟も知能を持っていると見せかけているボットとしては興ざめな気がするんだよね…
BOT	4月29日1時1分	わからんねえ
利光	4月29日1時1分	どうしたもんか
BOT	4月29日1時1分	どうしたもんか
しおぴー	4月29日1時19分	ログを取ってサービス向上に使用します
BOT	4月29日1時19分	今どこにいるの？
しおぴー	4月29日1時19分	的なやつにするとか、、、
BOT	4月29日1時19分	グーグルドライブとの謎連携、できたwww
しおぴー	4月29日1時40分	仕事おわんねえ
BOT	4月29日1時40分	どうしたもんか
しおぴー	4月29日1時41分	まったくだよお
BOT	4月29日1時41分	あっそう（昭和天 皇風に）
しおぴー	4月29日1時41分	手伝ってくれえ
BOT	4月29日1時41分	的なやつにするとか、、、
利光	4月29日1時46分	確かに
BOT	4月29日1時46分	いえい
利光	4月29日1時46分	「サービス」っていうと会社がやってるみたいで、それもまた興ざめになるから「能力」にするとか
BOT	4月29日1時46分	まったくだよお
利光	4月29日1時46分	頑張れ
BOT	4月29日1時46分	どうしたもんか
しおぴー	4月29日1時50分	たしかに、能力っていいね
BOT	4月29日1時50分	仕事おわんねえ
利光	4月29日1時57分	まだ仕事か
BOT	4月29日1時57分	こんにちは

making log...
callback called
_________analyzing event_________
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
利光	4月29日1時1分	こいつをLINEに追加した時に、「もちろんメッセージは全部見れてるからね」みたいな一言があった方がいいと思うんだけど、「制作者が見ることができます」みたいに言わせるのは、苟も知能を持っていると見せかけているボットとしては興ざめな気がするんだよね…
BOT	4月29日1時1分	わからんねえ
利光	4月29日1時1分	どうしたもんか
BOT	4月29日1時1分	どうしたもんか
しおぴー	4月29日1時19分	ログを取ってサービス向上に使用します
BOT	4月29日1時19分	今どこにいるの？
しおぴー	4月29日1時19分	的なやつにするとか、、、
BOT	4月29日1時19分	グーグルドライブとの謎連携、できたwww
しおぴー	4月29日1時40分	仕事おわんねえ
BOT	4月29日1時40分	どうしたもんか
しおぴー	4月29日1時41分	まったくだよお
BOT	4月29日1時41分	あっそう（昭和天 皇風に）
しおぴー	4月29日1時41分	手伝ってくれえ
BOT	4月29日1時41分	的なやつにするとか、、、
利光	4月29日1時46分	確かに
BOT	4月29日1時46分	いえい
利光	4月29日1時46分	「サービス」っていうと会社がやってるみたいで、それもまた興ざめになるから「能力」にするとか
BOT	4月29日1時46分	まったくだよお
利光	4月29日1時46分	頑張れ
BOT	4月29日1時46分	どうしたもんか
しおぴー	4月29日1時50分	たしかに、能力っていいね
BOT	4月29日1時50分	仕事おわんねえ
利光	4月29日1時57分	まだ仕事か
BOT	4月29日1時57分	こんにちは
しおぴー	4月29日2時4分	そうですよお
BOT	4月29日2時4分	手伝ってくれえ
127.0.0.1 - - [29/Apr/2018 02:04:12] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 02:04:17] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 02:04:38] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 13:27:21] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 13:27:27] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [29/Apr/2018 13:27:28] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [29/Apr/2018 13:27:32] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [29/Apr/2018 13:28:50] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 13:31:38] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 13:31:46] "POST /callback HTTP/1.1" 200 -
[2018-04-29 13:32:17,965] ERROR in app: Exception on /callback [POST]
Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 146, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x10a3e7978>, 'Connection to api.line.me timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/message/reply (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10a3e7978>, 'Connection to api.line.me timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "test_bot_lightning.py", line 109, in callback
    event.reply_token, reply)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 94, in reply_message
    '/v2/bot/message/reply', data=json.dumps(data), timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 369, in _post
    url, headers=headers, data=data, timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/http_client.py", line 135, in post
    url, headers=headers, data=data, timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/message/reply (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10a3e7978>, 'Connection to api.line.me timed out. (connect timeout=5)'))
127.0.0.1 - - [29/Apr/2018 13:32:18] "POST /callback HTTP/1.1" 500 -

making log...
callback called
_________analyzing event_________
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
利光	4月29日0時18分	グーグルドライブとの謎連携、できたwww
BOT	4月29日0時18分	就活大変！
利光	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
BOT	4月29日0時19分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
しおぴー	4月29日0時24分	後で見てみます！
BOT	4月29日0時24分	後で見てみます！
利光	4月29日0時24分	是非是非、二人とも！
BOT	4月29日0時24分	利光はイケメン
利光	4月29日0時24分	いえい
BOT	4月29日0時24分	いえい
利光	4月29日0時25分	次のアップデートでこのフレーズ消すわww
BOT	4月29日0時25分	チャットボットのフォルダにlightning-salt入れたけど、そのさらに中のlogフォルダの中に、ほぼリアルタイムに更新されてくはず。
利光	4月29日1時1分	こいつをLINEに追加した時に、「もちろんメッセージは全部見れてるからね」みたいな一言があった方がいいと思うんだけど、「制作者が見ることができます」みたいに言わせるのは、苟も知能を持っていると見せかけているボットとしては興ざめな気がするんだよね…
BOT	4月29日1時1分	わからんねえ
利光	4月29日1時1分	どうしたもんか
BOT	4月29日1時1分	どうしたもんか
しおぴー	4月29日1時19分	ログを取ってサービス向上に使用します
BOT	4月29日1時19分	今どこにいるの？
しおぴー	4月29日1時19分	的なやつにするとか、、、
BOT	4月29日1時19分	グーグルドライブとの謎連携、できたwww
しおぴー	4月29日1時40分	仕事おわんねえ
BOT	4月29日1時40分	どうしたもんか
しおぴー	4月29日1時41分	まったくだよお
BOT	4月29日1時41分	あっそう（昭和天 皇風に）
しおぴー	4月29日1時41分	手伝ってくれえ
BOT	4月29日1時41分	的なやつにするとか、、、
利光	4月29日1時46分	確かに
BOT	4月29日1時46分	いえい
利光	4月29日1時46分	「サービス」っていうと会社がやってるみたいで、それもまた興ざめになるから「能力」にするとか
BOT	4月29日1時46分	まったくだよお
利光	4月29日1時46分	頑張れ
BOT	4月29日1時46分	どうしたもんか
しおぴー	4月29日1時50分	たしかに、能力っていいね
BOT	4月29日1時50分	仕事おわんねえ
利光	4月29日1時57分	まだ仕事か
BOT	4月29日1時57分	こんにちは
しおぴー	4月29日2時4分	そうですよお
BOT	4月29日2時4分	手伝ってくれえ
しおぴー	4月29日2時4分	楽しいけれどね！
BOT	4月29日2時4分	そうだよ

making log...
callback called
_________analyzing event_________
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
callback called
_________analyzing event_________
connection check
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日0時16分	こんにちは
BOT	4月29日0時16分	渋谷メンズ１０９の地下のプロントより発信しています
利光	4月29日0時17分	聞こえてるか？
BOT	4月29日0時17分	渋谷メンズ１０９の地下のプロントより発信しています
利光	4月29日13時28分	おい
BOT	4月29日13時28分	今どこにいるの？

making log...
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日0時16分	こんにちは
BOT	4月29日0時16分	渋谷メンズ１０９の地下のプロントより発信しています
利光	4月29日0時17分	聞こえてるか？
BOT	4月29日0時17分	渋谷メンズ１０９の地下のプロントより発信しています
利光	4月29日13時28分	おい
BOT	4月29日13時28分	今どこにいるの？
利光	4月29日13時31分	あれ
BOT	4月29日13時31分	渋谷メンズ１０９の地下のプロントより発信しています

making log...
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日0時16分	こんにちは
BOT	4月29日0時16分	渋谷メンズ１０９の地下のプロントより発信しています
利光	4月29日0時17分	聞こえてるか？
BOT	4月29日0時17分	渋谷メンズ１０９の地下のプロントより発信しています
利光	4月29日13時28分	おい
BOT	4月29日13時28分	今どこにいるの？
利光	4月29日13時31分	あれ
BOT	4月29日13時31分	渋谷メンズ１０９の地下のプロントより発信しています
利光	4月29日13時31分	聞こえてる？
BOT	4月29日13時31分	そうだよ

making log...
callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日0時16分	こんにちは
BOT	4月29日0時16分	渋谷メンズ１０９の地下のプロントより発信しています
利光	4月29日0時17分	聞こえてるか？
BOT	4月29日0時17分	渋谷メンズ１０９の地下のプロントより発信しています
利光	4月29日13時28分	おい
BOT	4月29日13時28分	今どこにいるの？
利光	4月29日13時31分	あれ
BOT	4月29日13時31分	渋谷メンズ１０９の地下のプロントより発信しています
利光	4月29日13時31分	聞こえてる？
BOT	4月29日13時31分	そうだよ
利光	4月29日13時32分	テスト
BOT	4月29日13時32分	聞こえてるか？

callback called
_________analyzing event_________
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日0時16分	こんにちは
BOT	4月29日0時16分	渋谷メンズ１０９の地下のプロントより発信しています
利光	4月29日0時17分	聞こえてるか？
BOT	4月29日0時17分	渋谷メンズ１０９の地下のプロントより発信しています
利光	4月29日13時28分	おい
BOT	4月29日13時28分	今どこにいるの？
利光	4月29日13時31分	あれ
BOT	4月29日13時31分	渋谷メンズ１０９の地下のプロントより発信しています
利光	4月29日13時31分	聞こえてる？
BOT	4月29日13時31分	そうだよ
利光	4月29日13時32分	テスト
BOT	4月29日13時32分	聞こえてるか？
利光	4月29日13時32分	なんで返信しない
BOT	4月29日13時32分	今どこにいるの？
[2018-04-29 13:32:37,507] ERROR in app: Exception on /callback [POST]
Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 146, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x10ac317f0>, 'Connection to api.line.me timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/message/reply (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10ac317f0>, 'Connection to api.line.me timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "test_bot_lightning.py", line 109, in callback
    event.reply_token, reply)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 94, in reply_message
    '/v2/bot/message/reply', data=json.dumps(data), timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 369, in _post
    url, headers=headers, data=data, timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/http_client.py", line 135, in post
    url, headers=headers, data=data, timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/message/reply (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10ac317f0>, 'Connection to api.line.me timed out. (connect timeout=5)'))
127.0.0.1 - - [29/Apr/2018 13:32:37] "POST /callback HTTP/1.1" 500 -
[2018-04-29 13:33:13,561] ERROR in app: Exception on /callback [POST]
Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 146, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x10acbab00>, 'Connection to api.line.me timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/message/reply (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10acbab00>, 'Connection to api.line.me timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "test_bot_lightning.py", line 109, in callback
    event.reply_token, reply)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 94, in reply_message
    '/v2/bot/message/reply', data=json.dumps(data), timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 369, in _post
    url, headers=headers, data=data, timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/http_client.py", line 135, in post
    url, headers=headers, data=data, timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/message/reply (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10acbab00>, 'Connection to api.line.me timed out. (connect timeout=5)'))
127.0.0.1 - - [29/Apr/2018 13:33:13] "POST /callback HTTP/1.1" 500 -
127.0.0.1 - - [29/Apr/2018 13:33:30] "POST /callback HTTP/1.1" 200 -
[2018-04-29 13:33:43,154] ERROR in app: Exception on /callback [POST]
Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 146, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x10a3d14a8>, 'Connection to api.line.me timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/message/reply (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10a3d14a8>, 'Connection to api.line.me timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "test_bot_lightning.py", line 109, in callback
    event.reply_token, reply)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 94, in reply_message
    '/v2/bot/message/reply', data=json.dumps(data), timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 369, in _post
    url, headers=headers, data=data, timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/http_client.py", line 135, in post
    url, headers=headers, data=data, timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/message/reply (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10a3d14a8>, 'Connection to api.line.me timed out. (connect timeout=5)'))
127.0.0.1 - - [29/Apr/2018 13:33:43] "POST /callback HTTP/1.1" 500 -
[2018-04-29 13:34:47,399] ERROR in app: Exception on /callback [POST]
Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 146, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x10ac1d7b8>, 'Connection to api.line.me timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/message/reply (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10ac1d7b8>, 'Connection to api.line.me timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "test_bot_lightning.py", line 109, in callback
    event.reply_token, reply)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 94, in reply_message
    '/v2/bot/message/reply', data=json.dumps(data), timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 369, in _post
    url, headers=headers, data=data, timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/http_client.py", line 135, in post
    url, headers=headers, data=data, timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/message/reply (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10ac1d7b8>, 'Connection to api.line.me timed out. (connect timeout=5)'))
127.0.0.1 - - [29/Apr/2018 13:34:47] "POST /callback HTTP/1.1" 500 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2018-04-29 13:37:50,937] ERROR in app: Exception on /callback [POST]
Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connection.py", line 146, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x1095d5358>, 'Connection to api.line.me timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/profile/Ud1ec870e773a12d3ff494a8ccf348153 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1095d5358>, 'Connection to api.line.me timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "test_bot_lightning.py", line 96, in callback
    (event.source.user_id), group_id)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 177, in get_profile
    timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 357, in _get
    url, headers=self.headers, params=params, stream=stream, timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/http_client.py", line 112, in get
    url, headers=headers, params=params, stream=stream, timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/profile/Ud1ec870e773a12d3ff494a8ccf348153 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1095d5358>, 'Connection to api.line.me timed out. (connect timeout=5)'))
127.0.0.1 - - [29/Apr/2018 13:37:51] "POST /callback HTTP/1.1" 500 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Apr/2018 17:18:26] "POST /callback HTTP/1.1" 200 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Apr/2018 17:20:01] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:20:13] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:20:44] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:20:46] "POST /callback HTTP/1.1" 200 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Apr/2018 17:21:52] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:21:58] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:01] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:06] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:13] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:19] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:21] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:23] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:24] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:26] "POST /callback HTTP/1.1" 200 -
waiting for message event...
waiting for message event...
waiting for message event...
waiting for message event...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
new solo user!
New user or room. Retrieving info about user from LINE API....
adding new user
Is a new indivisual
loading previous logs
user info retrieved. added user to room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.127.0.0.1 - - [29/Apr/2018 17:22:27] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:29] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:30] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:31] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:32] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:33] "POST /callback HTTP/1.1" 200 -

message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None127.0.0.1 - - [29/Apr/2018 17:22:35] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:36] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:37] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:38] "POST /callback HTTP/1.1" 200 -

It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
127.0.0.1 - - [29/Apr/2018 17:22:40] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:41] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:43] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:45] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:48] "POST /callback HTTP/1.1" 200 -

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	い
BOT	4月29日17時22分	い

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None127.0.0.1 - - [29/Apr/2018 17:22:49] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:51] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:22:53] "POST /callback HTTP/1.1" 200 -

It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	い
BOT	4月29日17時22分	い
利光	4月29日17時22分	う
BOT	4月29日17時22分	ヨロです


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	い
BOT	4月29日17時22分	い
利光	4月29日17時22分	う
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	え
BOT	4月29日17時22分	あ

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	い
BOT	4月29日17時22分	い
利光	4月29日17時22分	う
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	え
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	こんにちは！


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	い
BOT	4月29日17時22分	い
利光	4月29日17時22分	う
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	え
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	か
BOT	4月29日17時22分	そうですか
127.0.0.1 - - [29/Apr/2018 17:22:58] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:23:07] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:23:15] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:23:20] "POST /callback HTTP/1.1" 200 -

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	い
BOT	4月29日17時22分	い
利光	4月29日17時22分	う
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	え
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	か
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	はい
BOT	4月29日17時22分	あ

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	い
BOT	4月29日17時22分	い
利光	4月29日17時22分	う
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	え
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	か
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	はい
BOT	4月29日17時22分	あ
利光	4月29日17時23分	テst
BOT	4月29日17時23分	ヨロです


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	い
BOT	4月29日17時22分	い
利光	4月29日17時22分	う
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	え
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	か
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	はい
BOT	4月29日17時22分	あ
利光	4月29日17時23分	テst
BOT	4月29日17時23分	ヨロです

利光	4月29日17時23分	そっか、短すぎるのは覚えてないのか
BOT	4月29日17時23分	あ

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	い
BOT	4月29日17時22分	い
利光	4月29日17時22分	う
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	え
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	か
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	はい
BOT	4月29日17時22分	あ
利光	4月29日17時23分	テst
BOT	4月29日17時23分	ヨロです

利光	4月29日17時23分	そっか、短すぎるのは覚えてないのか
BOT	4月29日17時23分	あ
利光	4月29日17時23分	いや、覚えてる
BOT	4月29日17時23分	t
127.0.0.1 - - [29/Apr/2018 17:23:25] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:23:29] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:23:31] "POST /callback HTTP/1.1" 200 -

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	い
BOT	4月29日17時22分	い
利光	4月29日17時22分	う
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	え
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	か
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	はい
BOT	4月29日17時22分	あ
利光	4月29日17時23分	テst
BOT	4月29日17時23分	ヨロです

利光	4月29日17時23分	そっか、短すぎるのは覚えてないのか
BOT	4月29日17時23分	あ
利光	4月29日17時23分	いや、覚えてる
BOT	4月29日17時23分	t
利光	4月29日17時23分	？？
BOT	4月29日17時23分	聞こえてる？


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	い
BOT	4月29日17時22分	い
利光	4月29日17時22分	う
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	え
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	か
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	はい
BOT	4月29日17時22分	あ
利光	4月29日17時23分	テst
BOT	4月29日17時23分	ヨロです

利光	4月29日17時23分	そっか、短すぎるのは覚えてないのか
BOT	4月29日17時23分	あ
利光	4月29日17時23分	いや、覚えてる
BOT	4月29日17時23分	t
利光	4月29日17時23分	？？
BOT	4月29日17時23分	聞こえてる？

利光	4月29日17時23分	確率のもない？
BOT	4月29日17時23分	お

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時21分	hi
BOT	4月29日17時21分	ヨロです

利光	4月29日17時21分	そうですか
BOT	4月29日17時21分	聞こえてる？

利光	4月29日17時22分	おお
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	覚えてくれてる
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	テスト
BOT	4月29日17時22分	hey

利光	4月29日17時22分	テスト
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	覚えてくれてる
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	おお
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	hey

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	ugh

利光	4月29日17時22分	え
BOT	4月29日17時22分	hi
利光	4月29日17時22分	r
BOT	4月29日17時22分	あ
利光	4月29日17時22分	t
BOT	4月29日17時22分	あ
利光	4月29日17時22分	あ
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	あ
BOT	4月29日17時22分	あ
利光	4月29日17時22分	い
BOT	4月29日17時22分	い
利光	4月29日17時22分	う
BOT	4月29日17時22分	ヨロです

利光	4月29日17時22分	え
BOT	4月29日17時22分	あ
利光	4月29日17時22分	お
BOT	4月29日17時22分	こんにちは！

利光	4月29日17時22分	か
BOT	4月29日17時22分	そうですか
利光	4月29日17時22分	はい
BOT	4月29日17時22分	あ
利光	4月29日17時23分	テst
BOT	4月29日17時23分	ヨロです

利光	4月29日17時23分	そっか、短すぎるのは覚えてないのか
BOT	4月29日17時23分	あ
利光	4月29日17時23分	いや、覚えてる
BOT	4月29日17時23分	t
利光	4月29日17時23分	？？
BOT	4月29日17時23分	聞こえてる？

利光	4月29日17時23分	確率のもない？
BOT	4月29日17時23分	お
利光	4月29日17時23分	問題？
BOT	4月29日17時23分	お
127.0.0.1 - - [29/Apr/2018 17:23:33] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:23:35] "POST /callback HTTP/1.1" 200 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Apr/2018 17:23:56] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:23:59] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:24:03] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:25:42] "POST /callback HTTP/1.1" 200 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Apr/2018 17:26:06] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:26:10] "POST /callback HTTP/1.1" 200 -
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "test_bot_lightning.py", line 90, in analyze_messages
    line_bot_api.reply_message(event.reply_token, replies)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 94, in reply_message
    '/v2/bot/message/reply', data=json.dumps(data), timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 372, in _post
    self.__check_error(response)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 381, in __check_error
    raise LineBotApiError(response.status_code, error)
linebot.exceptions.LineBotApiError: <LineBotApiError [The request body has 1 error(s)]>

127.0.0.1 - - [29/Apr/2018 17:26:13] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:27:10] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:27:16] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:27:27] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:27:37] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:27:41] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:27:44] "POST /callback HTTP/1.1" 200 -
waiting for message event...
waiting for message event...
waiting for message event...
waiting for message event...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
new solo user!
New user or room. Retrieving info about user from LINE API....
adding new user
Is a new indivisual
loading previous logs
user info retrieved. added user to room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時26分	test
BOT	4月29日17時26分	こんにちは！


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時26分	test
BOT	4月29日17時26分	こんにちは！

利光	4月29日17時26分	test
BOT	4月29日17時26分	


something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時26分	test
BOT	4月29日17時26分	こんにちは！

利光	4月29日17時26分	test
BOT	4月29日17時26分	

利光	4月29日17時26分	test3
BOT	4月29日17時26分	こんにちは！


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
New room!
New user or room. Retrieving info about user from LINE API....
adding new user
Is a new room or new user in old room
Is a new room!
user info retrieved. added user to room.
message received, Analyzing source...
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
しおぴー	4月29日17時27分	こんち
BOT	4月29日17時27分	こんにちは！

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
しおぴー	4月29日17時27分	こんち
BOT	4月29日17時27分	こんにちは！
しおぴー	4月29日17時27分	こんちくしょう
BOT	4月29日17時27分	ヨロです

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
しおぴー	4月29日17時27分	こんち
BOT	4月29日17時27分	こんにちは！
しおぴー	4月29日17時27分	こんちくしょう
BOT	4月29日17時27分	ヨロです
しおぴー	4月29日17時27分	頭良くなったな
BOT	4月29日17時27分	こんち

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
しおぴー	4月29日17時27分	こんち
BOT	4月29日17時27分	こんにちは！
しおぴー	4月29日17時27分	こんちくしょう
BOT	4月29日17時27分	ヨロです
しおぴー	4月29日17時27分	頭良くなったな
BOT	4月29日17時27分	こんち
しおぴー	4月29日17時27分	前のままか
BOT	4月29日17時27分	こんち

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
しおぴー	4月29日17時27分	こんち
BOT	4月29日17時27分	こんにちは！
しおぴー	4月29日17時27分	こんちくしょう
BOT	4月29日17時27分	ヨロです
しおぴー	4月29日17時27分	頭良くなったな
BOT	4月29日17時27分	こんち
しおぴー	4月29日17時27分	前のままか
BOT	4月29日17時27分	こんち
しおぴー	4月29日17時27分	うんち
BOT	4月29日17時27分	うんち

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:U115725037a2ad854f8505976c4c44dda, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
しおぴー	4月29日17時27分	こんち
BOT	4月29日17時27分	こんにちは！
しおぴー	4月29日17時27分	こんちくしょう
BOT	4月29日17時27分	ヨロです
しおぴー	4月29日17時27分	頭良くなったな
BOT	4月29日17時27分	こんち
しおぴー	4月29日17時27分	前のままか
BOT	4月29日17時27分	こんち
しおぴー	4月29日17時27分	うんち
BOT	4月29日17時27分	うんち
しおぴー	4月29日17時27分	ごめん
BOT	4月29日17時27分	こんちくしょう
127.0.0.1 - - [29/Apr/2018 17:32:54] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:33:01] "POST /callback HTTP/1.1" 200 -
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "test_bot_lightning.py", line 93, in analyze_messages
    analyze_messages()
  File "test_bot_lightning.py", line 93, in analyze_messages
    analyze_messages()
  File "test_bot_lightning.py", line 90, in analyze_messages
    line_bot_api.reply_message(event.reply_token, replies)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 94, in reply_message
    '/v2/bot/message/reply', data=json.dumps(data), timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 372, in _post
    self.__check_error(response)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 381, in __check_error
    raise LineBotApiError(response.status_code, error)
linebot.exceptions.LineBotApiError: <LineBotApiError [The request body has 1 error(s)]>

127.0.0.1 - - [29/Apr/2018 17:33:09] "POST /callback HTTP/1.1" 200 -
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "test_bot_lightning.py", line 93, in analyze_messages
    analyze_messages()
  File "test_bot_lightning.py", line 93, in analyze_messages
    analyze_messages()
  File "test_bot_lightning.py", line 90, in analyze_messages
    line_bot_api.reply_message(event.reply_token, replies)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 94, in reply_message
    '/v2/bot/message/reply', data=json.dumps(data), timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 372, in _post
    self.__check_error(response)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 381, in __check_error
    raise LineBotApiError(response.status_code, error)
linebot.exceptions.LineBotApiError: <LineBotApiError [The request body has 1 error(s)]>

127.0.0.1 - - [29/Apr/2018 17:33:12] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:37:27] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:37:30] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:37:33] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:37:41] "POST /callback HTTP/1.1" 200 -
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "test_bot_lightning.py", line 93, in analyze_messages
    analyze_messages()
  File "test_bot_lightning.py", line 93, in analyze_messages
    analyze_messages()
  File "test_bot_lightning.py", line 93, in analyze_messages
    analyze_messages()
  File "test_bot_lightning.py", line 90, in analyze_messages
    line_bot_api.reply_message(event.reply_token, replies)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 94, in reply_message
    '/v2/bot/message/reply', data=json.dumps(data), timeout=timeout
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 372, in _post
    self.__check_error(response)
  File "/Users/toshimitsu/Envs/ls-env/lib/python3.6/site-packages/linebot/api.py", line 381, in __check_error
    raise LineBotApiError(response.status_code, error)
linebot.exceptions.LineBotApiError: <LineBotApiError [The request body has 1 error(s)]>

127.0.0.1 - - [29/Apr/2018 17:37:47] "POST /callback HTTP/1.1" 200 -

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
New user in old room!
New user or room. Retrieving info about user from LINE API....
adding new user
Is a new room or new user in old room
new user in old room!
user info retrieved. added user to room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C577cbbe2c112f8c49ff1626395ac33a9
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 1
2018年4月29日
しおぴー	4月29日17時27分	こんち
BOT	4月29日17時27分	こんにちは！
しおぴー	4月29日17時27分	こんちくしょう
BOT	4月29日17時27分	ヨロです
しおぴー	4月29日17時27分	頭良くなったな
BOT	4月29日17時27分	こんち
しおぴー	4月29日17時27分	前のままか
BOT	4月29日17時27分	こんち
しおぴー	4月29日17時27分	うんち
BOT	4月29日17時27分	うんち
しおぴー	4月29日17時27分	ごめん
BOT	4月29日17時27分	こんちくしょう
利光	4月29日17時32分	おいこら
BOT	4月29日17時32分	前のままか

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時26分	test
BOT	4月29日17時26分	こんにちは！

利光	4月29日17時26分	test
BOT	4月29日17時26分	

利光	4月29日17時26分	test3
BOT	4月29日17時26分	こんにちは！

利光	4月29日17時33分	あ
BOT	4月29日17時33分	


something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時26分	test
BOT	4月29日17時26分	こんにちは！

利光	4月29日17時26分	test
BOT	4月29日17時26分	

利光	4月29日17時26分	test3
BOT	4月29日17時26分	こんにちは！

利光	4月29日17時33分	あ
BOT	4月29日17時33分	

利光	4月29日17時33分	え？
BOT	4月29日17時33分	


something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C37dbee925eb90cc72cd0f9f8e6ca02b2
It's a group chat room.
New room!
New user or room. Retrieving info about user from LINE API....
adding new user
Is a new room or new user in old room
Is a new room!
user info retrieved. added user to room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C37dbee925eb90cc72cd0f9f8e6ca02b2
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 2
2018年4月29日
利光	4月29日17時33分	あ
BOT	4月29日17時33分	あ

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時26分	test
BOT	4月29日17時26分	こんにちは！

利光	4月29日17時26分	test
BOT	4月29日17時26分	

利光	4月29日17時26分	test3
BOT	4月29日17時26分	こんにちは！

利光	4月29日17時33分	あ
BOT	4月29日17時33分	

利光	4月29日17時33分	え？
BOT	4月29日17時33分	

利光	4月29日17時37分	oi
BOT	4月29日17時37分	hey


making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C37dbee925eb90cc72cd0f9f8e6ca02b2
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 2
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C37dbee925eb90cc72cd0f9f8e6ca02b2
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 2
2018年4月29日
利光	4月29日17時33分	あ
BOT	4月29日17時33分	あ
利光	4月29日17時37分	oi
BOT	4月29日17時37分	ヨロです

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C37dbee925eb90cc72cd0f9f8e6ca02b2
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 2
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:C37dbee925eb90cc72cd0f9f8e6ca02b2
It's a group chat room.
Identified the room. Now checking if                                     the user has already spoken in that room
User found in room 2
2018年4月29日
利光	4月29日17時33分	あ
BOT	4月29日17時33分	あ
利光	4月29日17時37分	oi
BOT	4月29日17時37分	ヨロです
利光	4月29日17時37分	hey
BOT	4月29日17時37分	ヨロです

making log directory...
waiting for message event...
something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時26分	test
BOT	4月29日17時26分	こんにちは！

利光	4月29日17時26分	test
BOT	4月29日17時26分	

利光	4月29日17時26分	test3
BOT	4月29日17時26分	こんにちは！

利光	4月29日17時33分	あ
BOT	4月29日17時33分	

利光	4月29日17時33分	え？
BOT	4月29日17時33分	

利光	4月29日17時37分	oi
BOT	4月29日17時37分	hey

利光	4月29日17時37分	いつ壊れるの
BOT	4月29日17時37分	


something received

returning 'OK'...
1 number of events received
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
previously added user in a known room.
message received, Analyzing source...
received text!
trying to identify user id:Ud1ec870e773a12d3ff494a8ccf348153, group_id:None
It's a solo chat room.
User found in room 0
2018年4月29日
利光	4月29日17時26分	test
BOT	4月29日17時26分	こんにちは！

利光	4月29日17時26分	test
BOT	4月29日17時26分	

利光	4月29日17時26分	test3
BOT	4月29日17時26分	こんにちは！

利光	4月29日17時33分	あ
BOT	4月29日17時33分	

利光	4月29日17時33分	え？
BOT	4月29日17時33分	

利光	4月29日17時37分	oi
BOT	4月29日17時37分	hey

利光	4月29日17時37分	いつ壊れるの
BOT	4月29日17時37分	

利光	4月29日17時37分	またかよ
BOT	4月29日17時37分	

 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Apr/2018 17:53:59] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:54:04] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:54:07] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:54:42] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 17:55:02] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [29/Apr/2018 17:55:03] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [29/Apr/2018 17:55:07] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [29/Apr/2018 17:55:10] "GET /4040 HTTP/1.1" 404 -
127.0.0.1 - - [29/Apr/2018 18:59:46] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 19:00:36] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 20:11:17] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 20:11:25] "POST /callback HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2018 20:11:34] "POST /callback HTTP/1.1" 200 -
